server:
  port: 8080

mybatis:
  type-aliases-package: com.czhou.model
  mapper-locations: classpath:mapping/*.xml

spring:
  datasource:
    name: employee
    url: jdbc:mysql://localhost:3306/employee?useSSL=false&serverTimeZone=UTC&characterEncoding=UTF8
    username: root
    password: Root1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  swagger:
    base-package: com.czhou
    enabled: true

#pagehelper:
#  reasonable: true
#  dialect: mysql
#  params: count=countSql
#  support-methods-arguments: true



